spring.application.name=InterviewIQ

server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/interviewiq
spring.datasource.username=admin
spring.datasource.password=password

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration